language: python

python:
  - "2.7"

# We don't need sudo
sudo: false

addons:
  srcclr: true

# command to run prerequisites
before_install:
  - pip install cython

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

# command to run tests
script:
  - coverage run --include './*' --omit 'manage.py' --source '.' -m manage test

# command to run after tests
after_success:
  - coveralls
